settings:
  digits: 3
  itemformat: yaml
  prefix: REQ
  sep: ''
attributes:
  reviewed:
    - short-name
  defaults:
    short-name: ''
    doc:
      name: simple
      title: Requirements for _simple_
      ref: ''
      by: tdeveloper
      major: '1'
      minor: A
      copyright: tdeveloper
  publish:
    - commentary
    - rationale
    - normative
