settings:
  digits: 3
  itemformat: markdown
  parent: REQ
  prefix: SDD
  sep: ''
extensions:
  item_sha_required: true  # sha256
attributes:
  defaults:
    doc:
      name: SW Design
      title: SW Design Description
      ref: ''
      by: tdeveloper
      major: '1'
      minor: A
      copyright: tdeveloper
  publish:
    - commentary
    - rationale
